### PR TITLE
Added zoom function with some tests. Needs interpolation function

### PR DESCRIPTION
**Pull request by crisely09**

### CODE REVIEW

**Comment by lelemmen** [comment]
Travis only fails because of coverage in flik/linesearch/input.py.

**Comment by kimt33** [comment]
So I made whatever changes I was willing to make. The coverage was not passing because the code was not being tested. The test would fail at line 64, meaning that everything that comes afterwards were not tested. There was also a bug in the algorithm:
`tmp_step = func(var) + const1*alpha_one*grad(var)` returns an array. I guessed that it was supposed to be `func(var + const1*alpha_one*grad(var))`. After fixing these mistakes, the code still doesn't converge, so the constants and alphas should be tweaked or there is a bug in the algorithm.

**Comment by kimt33** [comment]
I am not merging this until the code gets fully tested.

**Comment by crisely09** [comment]
Alright, I have to take a look at it again. Be at the lab soon

**Comment by crisely09** [comment]
I got my python3 with numpy and nose, sorry... I'll do the test in my computer, yesterday I just didn't have the energy/will.

**Comment by kimt33** [comment]
I've rebased your commits on top of current master. I also squashed all your commits.

**Comment by kimt33** [comment]
I'm merging this so we can have all the code to PR onto the main branch. These will be used as reference for refactoring linesearch later.

**Pull request merged**
