### PR TITLE
Dogleg method.

### PR DESCRIPTION
**Pull request by crisely09**
While writing the tests I realized it was much easier if it was just a method instead of a class, maybe we could discuss it again?

### CODE REVIEW

**Comment by lelemmen** [comment]
I added some comments on the Cauchy (PR #21), these are applicable to here as well: variable names to distinguish better from callable and vector/matrix and tau instead of tao.

**Comment by crisely09** [comment]
I am just missing a way to "refresh" the attributes if one of the arguments is changed.

**Comment by crisely09** [comment]
@kimt33  I think this is also ready to merge, according to the report it fails because of the sub_problem errors.

**Comment by kimt33** [comment]
Could you fix the Travis complaints (pydocstyle) and rebase/squash please?

**Pull request merged**
